### ISSUE TITLE
version 0.9.9 ependencies error

### ISSUE THREAD

**Issue by hendlake8** [ONE-AdMax/ONEAdMax-Unity#1]
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':launcher:releaseRuntimeClasspath'.
   > Could not find com.oneadmax.sdk:sdk-ads-unity:0.9.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - https://repo.maven.apache.org/maven2/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - https://s01.oss.sonatype.org/content/repositories/releases/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - https://repo.onestore.co.kr/repository/onestore-sdk-public/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - file:/E:/PlanE/Projects/ClientPrj/Assets/GeneratedLocalRepo/Firebase/m2repository/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - https://maven.google.com/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - file:/E:/PlanE/Projects/ClientPrj/Assets/GeneratedLocalRepo/GooglePlayGames/Editor/m2repository/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - https://artifact.bytedance.com/repository/pangle/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - file:/C:/Users/hendlake/.m2/repository/com/oneadmax/sdk/sdk-ads-unity/0.9.8/sdk-ads-unity-0.9.8.pom
       - file:/E:/PlanE/Projects/ClientPrj/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/sdk-ads-unity-0.9.8.jar
       - file:/E:/PlanE/Projects/ClientPrj/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/libs/sdk-ads-unity.jar
     Required by:
         project :launcher > project :unityLibrary

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':unityLibrary:generateReleaseRFile'.
> Could not resolve all files for configuration ':unityLibrary:releaseCompileClasspath'.
   > Could not find com.oneadmax.sdk:sdk-ads-unity:0.9.8.
     Required by:
         project :unityLibrary

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

When using the 'Assets > External Dependency Manager > Android Resolver > Force Resolve' menu, the following line is added to the mainTemplate.gradle file: 'implementation 'com.oneadmax.sdk:sdk-ads-unity:0.9.8' // Assets/OneStoreCorpPlugins/ONEAdMax/Editor/ONEAdMaxDependencies.xml:6'. This causes a build error because it fails to find the 0.9.8 file.

If you change it to 'implementation 'com.oneadmax.sdk:sdk-ads-unity:0.9.9' // Assets/OneStoreCorpPlugins/ONEAdMax/Editor/ONEAdMaxDependencies.xml:6', the build completes successfully.

**Comment by Dev1000146** [comment]
We made a mistake.
We've fixed it and re-uploaded with version 0.9.9
